config/routes.rb
Rails.application.routes.draw do
  get 'hangouts/index'
  get 'my_registrations/create'
  devise_for :users, controllers: { registrations: "my_registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
  resources :follow_requests do
    put "accept", on: :member
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :profile
  resources :users, only: :index
  resources :messages, only: [:create]
  resources :hangouts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: {minimum: 1}
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images
  has_rich_text :rich_body

  validates :title, presence: true, length: {minimum: 1, maximum: 200}
  validates :body, presence: true, length: {minimum: 1}

  def resize_500(image)
    image.variant(resize_to_limit: [500, 500]).processed
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar do |pic|
    pic.variant :thumb, resize_to_limit: [150, 150]
    pic.variant :thumb_300, resize_to_limit: [300, 300]
  end

  def pic_200(picture)
    picture.variant(resize_to_limit: [200, 200]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_follow_requests, foreign_key: "sender_id", class_name: "FollowRequest", dependent: :destroy
  has_many :received_follow_requests, foreign_key: "receiver_id", class_name: "FollowRequest", dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile
  has_many :messages
  
  def cannot_send_follow_request?(current_user)
    current_user.sent_follow_requests.find_by(receiver_id: self.id)    
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build
  end

  def create
    @post = Post.find(params[:post_id])
    params[:comment][:user_id] = current_user.id
    @comment = @post.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user == current_user
      respond_to do |format|
        if @comment.destroy
          format.turbo_stream
        else
          redirect_to post_path(@comment.post)
        end
      end
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    @post = Post.find(params[:post_id])    
    @like.save
    @like_count = @post.likes.count
    respond_to do |format| 
      format.turbo_stream
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:post_id])
    @post = Post.find(params[:post_id])    
    @like.destroy
    @like_count = @post.likes.count
    respond_to do |format| 
      format.turbo_stream
    end
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    good_ids = allowed_user_ids
    @posts = Post.where('updated_at > ?', Time.now - 7.days).where(user_id: good_ids).order(updated_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like_count = @post.likes.count
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :img_url, :rich_body, :images => [])
  end

  def allowed_user_ids
    acceptedRequests = FollowRequest.where(accepted: true, sender_id: current_user.id)
    allowed_user_ids = acceptedRequests.pluck(:receiver_id)
    allowed_user_ids << current_user.id
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params.merge(user_id: current_user.id))
    if @profile.save
      redirect_to @profile
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @profile = current_user.profile    
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to @profile
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show
    @profile = current_user.profile    
  end


  private

  def profile_params
    params.require(:profile).permit(:user_id, :user_name, :about, :location, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/follow_requests_helper.rb
module FollowRequestsHelper
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% if comment && comment.user %>
  <div id="comment-<%= comment.id %>">
    <%= comment.user.email %>: <%= comment.body %>
    <% if comment.user == current_user %> 
      <%= link_to "Remove Comment", post_comment_path(comment.post, comment), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } %>
    <% end %>
  </div>

<% end %>

app/views/comments/_comment_form.html.erb
<%= form_with model: [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comment-box", @comment %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}"%>

app/views/comments/new.html.erb
<turbo-frame id="new-comment">
  <%= render "comment_form" %>
</turbo-frame>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace "like-box" do %>
  <div id="like-box">
    <% if @like_count > 0 %>
      <div>
        <%= @like_count %> people liked this post
      </div>
    <% end %>
    <%= link_to "unlike", post_like_path(@post, @like), data: {turbo_method: :delete} %>
  </div>
<% end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.replace "like-box" do %>  
  <div id="like-box">
    <% if @like_count > 0 %>
      <div>
        <%= @like_count %> people liked this post
      </div>
    <% end %>
    <%= link_to "like", post_likes_path(@post, Like.new), data: {turbo_method: :post} %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<hr> 
<div class="post-window">
  <%= link_to post_path(post) do %>
    <p><%= post.user != current_user ? post.user.email : "You Posted"%></p>
    <div>
      <%= post.title %>
    </div>
    <% if post.img_url.present? %>
      <div class="image-container">
        <%= image_tag post.img_url, class: "post-img" %>
      </div>
    <% end %>
    <div><%= post.rich_body %></div>
    <% if post.images.present? %>
      <div class="image-container">
        <% post.images.each do |image| %>
          <%= image_tag(post.resize_500(image)) %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div> 

app/views/posts/_post_form.html.erb
<%= form_with model: @post, html: { class: "post-form" } do |f| %>
  <div class="form-input">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-input">
    <%= f.label :body %>
    <%= f.text_area :body, size: '100x20', class: "form-control" %>
  </div>
  <div class="form-input">
    <%= f.rich_text_area :rich_body, class: "form-control" %>
  </div>
  <div class="form-input">
    <%= f.label :images %>
    <%= f.file_field :images, multiple: true, class: "form-control" %>
  </div>
  <div class="form-input">
    <%= f.label :img_url %>
    <%= f.text_field :img_url, placeholder: "Optional", class: "form-control" %>
  </div>
  <div class="form-input">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "post_form" %>

app/views/posts/index.html.erb
<div><%= link_to "New Post", new_post_path %></div>
<%= render @posts %>

app/views/posts/new.html.erb
<%= render "post_form" %>

app/views/posts/show.html.erb
<h3><%= @post.title %></h3>
<% if @post.img_url.present? %>
  <%= image_tag @post.img_url, class: "post-img" %>
<% end %>
<div>
  <%= @post.body %>
</div>
<div>
  <%= @post.rich_body %>
</div>

<% if @post.images.present? %>
  <hr>
  <div>
    <% @post.images.each do |image| %>
      <div><%= link_to image_tag(@post.resize_500(image)), image %></div>
    <% end %>
  </div>
<% end %>

<hr>
<div id="like-box">
  <% if @like_count > 0 %>
    <div>
      <%= @like_count %> people liked this post
    </div>
  <% end %>
  <% if @like %>
    <%= link_to "unlike", post_like_path(@post, @like), data: {turbo_method: :delete} %>
  <% else %>
    <%= link_to "like", post_likes_path(@post, @like), data: {turbo_method: :post} %>
  <% end %>
</div>

<hr>
<div>
  <%= turbo_frame_tag "new-comment", src: new_post_comment_path(@post, @post.comments.build) %>
</div>

<% if @comments.present? %>  
  <h3>Comments on post:</h3>
  <div id="comment-box">
    <%= render @comments %>
  </div>
<% end %>

<hr>
<% if @post.user_id == current_user.id %>
  <div>
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>

  <div>
    <%= link_to "Delete Post", post_path(@post), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>
<% end %>

app/views/users/_user.html.erb
<% if user %>
  <div>    
    <% if !user.cannot_send_follow_request?(current_user) %>
      <p>
        <%= form_with model:FollowRequest.new, url:follow_requests_path, method: :post do |f| %>
          <%= f.hidden_field :receiver_email, value: user.email %>
          <%= f.hidden_field :from_users, value: true %>
          <%= user.email %>
          <%= f.submit "Send follow request" %>
        <% end %>
      </p>
    <% else %>
      <p>
        <% follow_request = user.cannot_send_follow_request?(current_user) %>
        <%= user.email %>
        <%= link_to button_tag("Remove request"), follow_request_path(follow_request), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render @users %>