config/routes.rb
Rails.application.routes.draw do
  get 'hangouts/index'
  get 'my_registrations/create'
  devise_for :users, controllers: { registrations: "my_registrations" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
  resources :follow_requests do
    put "accept", on: :member
  end

  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:new, :create, :destroy]
  end

  resources :profile
  resources :users, only: :index
  resources :messages, only: [:create]
  resources :hangouts, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true, length: {minimum: 1}
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images
  has_rich_text :rich_body

  validates :title, presence: true, length: {minimum: 1, maximum: 200}
  validates :body, presence: true, length: {minimum: 1}

  def resize_500(image)
    image.variant(resize_to_limit: [500, 500]).processed
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar do |pic|
    pic.variant :thumb, resize_to_limit: [150, 150]
    pic.variant :thumb_300, resize_to_limit: [300, 300]
  end

  def pic_200(picture)
    picture.variant(resize_to_limit: [200, 200]).processed
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sent_follow_requests, foreign_key: "sender_id", class_name: "FollowRequest", dependent: :destroy
  has_many :received_follow_requests, foreign_key: "receiver_id", class_name: "FollowRequest", dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :profile
  has_many :messages
  
  def cannot_send_follow_request?(current_user)
    current_user.sent_follow_requests.find_by(receiver_id: self.id)    
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @like = current_user.likes.build(post_id: params[:post_id])
    @post = Post.find(params[:post_id])    
    @like.save
    @like_count = @post.likes.count
    respond_to do |format| 
      format.turbo_stream
    end
  end

  def destroy
    @like = current_user.likes.find_by(post_id: params[:post_id])
    @post = Post.find(params[:post_id])    
    @like.destroy
    @like_count = @post.likes.count
    respond_to do |format| 
      format.turbo_stream
    end
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    good_ids = allowed_user_ids
    @posts = Post.where('updated_at > ?', Time.now - 7.days).where(user_id: good_ids).order(updated_at: :desc)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like_count = @post.likes.count
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to posts_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :img_url, :rich_body, :images => [])
  end

  def allowed_user_ids
    acceptedRequests = FollowRequest.where(accepted: true, sender_id: current_user.id)
    allowed_user_ids = acceptedRequests.pluck(:receiver_id)
    allowed_user_ids << current_user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/hangouts_helper.rb
module HangoutsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>      
    <nav>
      <div class="left">          
        <% if current_user %>
          <%= link_to "Facebook Clone", root_path %>
          <%= link_to "Follow Requests", follow_requests_path %>
          <%= link_to "Find Others", users_path %>
          <%= link_to "Public Chat Room", hangouts_path %>
          <% if current_user.profile %>
            <%= link_to "Profile", profile_path(current_user.profile) %>
          <% else %>
            <%= link_to "Create Profile", new_profile_path %>
          <% end %>
        <% end %>
      </div>
      <div class="right">
        <% if current_user %>
          <%= link_to "Logout", destroy_user_session_path, data: {
          turbo_method: :delete,
        } %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
      </div>
      
    </nav>
    <hr>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <p class="error"><%= flash[:error] %></p>
    <main><%= yield %></main>
  </body>
</html>